[build]
  base = "Frontend-Dev Eksamen 2"
  command = "npm run build:site"
  publish = "Frontend-Dev Eksamen 2/dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[post_processing]
  skip_processing = true
