[build]
  base = "JeanettKM_Eksamen_FD-Copy/Frontend-Dev Eksamen 2"
  command = "npm run build"
  publish = "Frontend-Dev Eksamen 2/dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
